### 1. Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np

In [2]:
m1 = np.matrix([[1,2,3],[4,5,6],[8,7,9]])

In [3]:
m2 = np.matrix([[1,1,1],[2,2,2],[3,3,3]])

In [4]:
m1+m2

matrix([[ 2,  3,  4],
        [ 6,  7,  8],
        [11, 10, 12]])

In [5]:
## method-2
M1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
M2 = np.array([[1,1,1],[2,2,2],[3,3,3]])
M1+M2

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

### 2. Write a Python Program to Multiply Two Matrices?

In [6]:
m1 = np.matrix([[1,2,3],[1,4,9],[1,8,27]])
m2 = np.matrix([[1,1,1],[2,2,2],[3,3,3]])
m1*m2

matrix([[14, 14, 14],
        [36, 36, 36],
        [98, 98, 98]])

### 3. Write a Python Program to Transpose a Matrix?

In [7]:
m1 = np.matrix([[11,44,77],[22,55,88],[33,66,99]])

In [8]:
m1

matrix([[11, 44, 77],
        [22, 55, 88],
        [33, 66, 99]])

In [9]:
### Method-1
print(m1.transpose())

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [10]:
### Method -2
print(m1.T)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


### 4. Write a Python Program to Sort Words in Alphabetic Order?

In [11]:
lst = ["A","a","E","f","K","z","l","d","b","c"]

In [12]:
lst = ["A","a","E","f","K","z","l","d","b","c"]
s_lst = []
for i in range(len(lst)):
    s_lst.append(ord(lst[i]))
s_lst.sort()
[chr(j) for j in s_lst]

['A', 'E', 'K', 'a', 'b', 'c', 'd', 'f', 'l', 'z']

In [13]:
s = "Vamshi nalla krishna full Stack Data science"
new_sort = s.lower().split(" ")
new_sort.sort()
print(new_sort)

['data', 'full', 'krishna', 'nalla', 'science', 'stack', 'vamshi']


### 5. Write a Python Program to Remove Punctuation From a String?

In [14]:
User_input = str(input("Please enter only string input ::"))
punctuations = """!()-[]{};:'"\,<>./?@#$%^&*_~"""
final_string = ''
for character in User_input:
    if character not in punctuations:
        final_string+=character
print("The new string after removing punctuations :::: \n",final_string)

Please enter only string input ::Ineuron***!@#$%^& krish$$naik!!!! Sudhanshu(((::
The new string after removing punctuations :::: 
 Ineuron krishnaik Sudhanshu
